# Recommender Systems Deep-Dive Lab

There are many different approaches that we can take when creating recommender systems. In the Intro to Recommender Systems lesson and lab, we put together a user similarity based recommender that first calculated the similarities between users and then leveraged a rank-based item recommender within each group of similar customers. In other words, for a given user, our recommender found the top 5 customers who were the most similar to them, aggregated and ranked the purchases of those 5 customers, and then recommended the top 5 most popular products among that group of similar users to the customer.

In this lab, we are going to start out with the same data set, but we are going to dive deeper into the analysis of customers and products and look at an alternative way to generate recommendations.

We will begin by importing everything we will need for this lab (libraries, data set, etc.).

In [1]:
import pandas as pd
from scipy.spatial.distance import pdist, squareform

In [2]:
data = pd.read_csv('/Users/arnoldoleyson/Desktop/Ironhack/Labs/lab-recommender-deepdive/data/customer_product_sales.csv')
data.head()

,CustomerID,FirstName,LastName,SalesID,ProductID,ProductName,Quantity
0,61288,Rosa,Andersen,134196,229,Bread - Hot Dog Buns,16
1,77352,Myron,Murray,6167892,229,Bread - Hot Dog Buns,20
2,40094,Susan,Stevenson,5970885,229,Bread - Hot Dog Buns,11
3,23548,Tricia,Vincent,6426954,229,Bread - Hot Dog Buns,6
4,78981,Scott,Burch,819094,229,Bread - Hot Dog Buns,20

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68584 entries, 0 to 68583
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   68584 non-null  int64
 1   FirstName    68584 non-null  object
 2   LastName     68584 non-null  object
 3   SalesID      68584 non-null  int64
 4   ProductID    68584 non-null  int64
 5   ProductName  68584 non-null  object
 6   Quantity     68584 non-null  int64
dtypes: int64(4), object(3)
memory usage: 3.7+ MB

## Data Preparation

We will then put together the foundational transformations of the data that we will need to eventually produce recommendations. The steps in this section should be familiar to you, as you would have had to tranform the data in this manner to create the user similarity based recommender in the Intro to Recommender Systems lab.

First, we will create a data frame that contains the total quantity of each product purchased by each customer.

In [4]:
customer_products = data.groupby(['CustomerID', 'ProductName']).agg({'Quantity':'sum'}).reset_index()
customer_products

       CustomerID                    ProductName  Quantity
0              33               Apricots - Dried         1
1              33              Assorted Desserts         1
2              33        Bandage - Flexible Neon         1
3              33  Bar Mix - Pina Colada, 355 Ml         1
4              33         Beans - Kidney, Canned         1
...           ...                            ...       ...
63623       98200                   Vol Au Vents        50
63624       98200                  Wasabi Powder        25
63625       98200       Wine - Fume Blanc Fetzer        25
63626       98200  Wine - Hardys Bankside Shiraz        25
63627       98200        Yogurt - French Vanilla        25

[63628 rows x 3 columns]

Then, we want to create a matrix that has customers on one axis, products on the other, and the quantity purchased as the values. There will be many instances where a customer has not purchased a product, which by default will be expressed with a null value. We will want to replace those nulls with zeros by appending `.fillna(0)` to our pivot table.

In [5]:
prod_cust_pivot = customer_products.pivot_table(values = 'Quantity', 
                                                columns = 'CustomerID', 
                                                index = 'ProductName', 
                                                aggfunc = 'sum').fillna(0)

prod_cust_pivot.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Appetizer - Mini Egg Roll, Shrimp",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Appetizer - Mushroom Tart,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0
Appetizer - Sausage Rolls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,25.0,25.0,25.0,0.0,25.0,0.0
Apricots - Dried,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In the pivot table we created, the rows represent the products and the columns represent the customers. Depending on what need to do with the matrix, we may instead need to transpose it so that the rows represent customers and the columns to represent products. We can do this easily by appending `.T` to our product customer matrix.

In [6]:
cust_prod_pivot = prod_cust_pivot.T
cust_prod_pivot.head()

ProductName,Anchovy Paste - 56 G Tube,"Appetizer - Mini Egg Roll, Shrimp",Appetizer - Mushroom Tart,Appetizer - Sausage Rolls,Apricots - Dried,Apricots - Halves,Apricots Fresh,Arizona - Green Tea,Artichokes - Jerusalem,Assorted Desserts,...,"Wine - White, Colubia Cresh","Wine - White, Mosel Gold","Wine - White, Schroder And Schyl",Wine - Wyndham Estate Bin 777,Wonton Wrappers,Yeast Dry - Fermipan,Yoghurt Tubes,"Yogurt - Blueberry, 175 Gr",Yogurt - French Vanilla,Zucchini - Yellow
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
264,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
356,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
412,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

Another thing we may want to do is normalize the values across rows or columns of the matrix so that all the values are between 0 and 1. Doing this for customers would help us identify customers that may have purcahsed a similar mix of products even though some of those customers may have purchased large quantities while other may have purchased smaller quantities. Doing this for products would help us better identify products that have been purchased by similar groups of customers regardless of the quantities purchased.

We can normalize across rows for each matrix as follows.

In [7]:
prod_cust_pivot = prod_cust_pivot.div(prod_cust_pivot.sum(axis = 1), axis = 0)
cust_prod_pivot = cust_prod_pivot.div(cust_prod_pivot.sum(axis = 1), axis = 0)

## User Similarity Based Recommendations

The next step in creating recommendations is calculating similarities. For our user similarity based recommender, we calculated them between customers.

In [8]:
cust_dist = pd.DataFrame(1/(1 + squareform(pdist(cust_prod_pivot, 'euclidean'))),
                         index=cust_prod_pivot.index, columns = cust_prod_pivot.index)

cust_dist.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,1.000000,0.854082,0.859145,0.852783,0.856118,0.853239,0.849549,0.848801,0.851224,0.849892,...,0.855130,0.846812,0.850301,0.841254,0.852221,0.846485,0.852848,0.847637,0.856465,0.851614
200,0.854082,1.000000,0.857935,0.855900,0.856445,0.853129,0.863562,0.850521,0.857381,0.856621,...,0.864397,0.856014,0.862447,0.854629,0.856670,0.854046,0.868990,0.857312,0.861508,0.857184
264,0.859145,0.857935,1.000000,0.851801,0.860050,0.851262,0.855847,0.846677,0.854206,0.848997,...,0.861268,0.850766,0.854178,0.848507,0.858909,0.860153,0.859773,0.854246,0.864699,0.853668
356,0.852783,0.855900,0.851801,1.000000,0.852571,0.849431,0.853831,0.851902,0.847607,0.846328,...,0.857171,0.848015,0.852222,0.847706,0.851413,0.851289,0.851219,0.852260,0.860721,0.854377
412,0.856118,0.856445,0.860050,0.852571,1.000000,0.855755,0.858976,0.857221,0.854857,0.855991,...,0.859117,0.862847,0.854943,0.850044,0.858385,0.856629,0.855052,0.856608,0.865269,0.862253

Once we had our similarity matrix, then we could produce recommendations for each user and package all the recommendations into a data frame.

In [9]:
recommendations = {}
customers = list(customer_products['CustomerID'].unique())

for customer in customers:
    similar_cust = list(cust_dist[customer].sort_values(ascending = False)[1:].head().index)
    sim_cust_prod = customer_products[customer_products['CustomerID'].isin(similar_cust)]
    grouped = sim_cust_prod.groupby('ProductName').agg({'Quantity':'sum'})
    ranked_products = grouped.sort_values('Quantity', ascending = False).reset_index()
    
    merged = pd.merge(ranked_products, pd.DataFrame(cust_prod_pivot.T[customer]), on = 'ProductName')
    merged.columns = ['ProductName', 'Quantity', 'Purchased']
    recs = merged[merged['Purchased'] == 0].head()
    recommendations[customer] = list(recs['ProductName'])

user_recs = pd.DataFrame.from_dict(recommendations, orient = 'index').reset_index()
user_recs.columns = ['CustomerID', 'Rec1', 'Rec2', 'Rec3', 'Rec4', 'Rec5']
user_recs.head()

,CustomerID,Rec1,Rec2,Rec3,Rec4,Rec5
0,33,Wine - Redchard Merritt,Bread - Calabrese Baguette,"Thyme - Lemon, Fresh",Milk Powder,Ecolab - Lime - A - Way 4/4 L
1,200,Sauce - Demi Glace,General Purpose Trigger,Cookie Chocolate Chip With,Chef Hat 20cm,Pasta - Angel Hair
2,264,Ezy Change Mophandle,Eggplant - Asian,Scallops - 10/20,Cinnamon Buns Sticky,Wine - Ej Gallo Sierra Valley
3,356,Tea - Herbal Sweet Dreams,Curry Paste - Madras,Tea - English Breakfast,Juice - Orange,Ecolab - Lime - A - Way 4/4 L
4,412,Cake - Box Window 10x10x2.5,Beef - Montreal Smoked Brisket,Bread - Raisin Walnut Oval,"Mushroom - Trumpet, Dry",Cheese - Mix

## Deeper Dive Into Our User Similarity Recommendations

Let's deconstruct what we've done and take a deeper dive into how we put this together. Doing this will equip us with the knowledge to be able to put together an item-based similarity recommender in the next section. 

After creating an empty dictionary to store our recommendations and getting a unique list of customer IDs to iterate through, we are first identifying the top 5 similar customers to the customer we are trying to generate recommendations for. Let's plug in customer ID 33 and see what results we get.

In [10]:
similar_cust = list(cust_dist[33].sort_values(ascending = False)[1:6].index)
similar_cust

[60862, 27672, 6001, 79458, 33759]

What we get is a list containing the 5 customer IDs of the customers whose purchase behavior is most similar to customer 33. We then go back to our customer_products data frame and select just the purchases where the customer ID is in our list of similar customers. We aggregate on product name, summing up the total quantity purchased of each product by all 5 similar customers, and then we rank them by sorting in descending order by the total quantity.

In [11]:
sim_cust_prod = customer_products[customer_products['CustomerID'].isin(similar_cust)]
grouped = sim_cust_prod.groupby('ProductName').agg({'Quantity':'sum'})
ranked_products = grouped.sort_values('Quantity', ascending = False).reset_index()
ranked_products.head()

                  ProductName  Quantity
0     Wine - Redchard Merritt        59
1                      Cassis        58
2  Bread - Calabrese Baguette        45
3  Wine - Crozes Hermitage E.        45
4        Thyme - Lemon, Fresh        42

We now have a ranked list of products that similar customers have purchased, but we haven't taken into consideration yet whether our target customer already purchases any of those items. We want to recommend them items that they might like but haven't purchased before. So we will merge the list of ranked products with our target customer's purchase list and keep only the records for items that the customer has not purchased. These will be the items that we recommend to the customer.

In [12]:
merged = pd.merge(ranked_products, pd.DataFrame(cust_prod_pivot.T[33]), on = 'ProductName')
merged.columns = ['ProductName', 'Quantity', 'Purchased']
recs = merged[merged['Purchased'] == 0].head()
recs

                      ProductName  Quantity  Purchased
0         Wine - Redchard Merritt        59        0.0
2      Bread - Calabrese Baguette        45        0.0
4            Thyme - Lemon, Fresh        42        0.0
9                     Milk Powder        39        0.0
10  Ecolab - Lime - A - Way 4/4 L        39        0.0

## Item Similarity Based Recommendations

In this section, you will create an item similarity based recommender system in a step-by-step fashion. Whereas our user similarity based recommender leveraged similarities between customers, this recommender will utilize similarities between products. You already have all the tools in your toolbox, so follow each of the steps below to complete this lab.

### Step 1: Create a product distance matrix.

In [13]:
customer_products2 = data.groupby(['ProductName', 'CustomerID']).agg({'Quantity':'sum'}).reset_index()
customer_products2

                     ProductName  CustomerID  Quantity
0      Anchovy Paste - 56 G Tube         639         1
1      Anchovy Paste - 56 G Tube         883         1
2      Anchovy Paste - 56 G Tube         891         1
3      Anchovy Paste - 56 G Tube        2566         1
4      Anchovy Paste - 56 G Tube        2902         1
...                          ...         ...       ...
63623          Zucchini - Yellow       94910        25
63624          Zucchini - Yellow       95078        25
63625          Zucchini - Yellow       95372        50
63626          Zucchini - Yellow       96024        25
63627          Zucchini - Yellow       96666        25

[63628 rows x 3 columns]

In [14]:
prod_cust_pivot2 = customer_products2.pivot_table(values = 'Quantity', 
                                                columns = 'ProductName', 
                                                index = 'CustomerID', 
                                                aggfunc = 'sum').fillna(0)

prod_cust_pivot2.head()

ProductName,Anchovy Paste - 56 G Tube,"Appetizer - Mini Egg Roll, Shrimp",Appetizer - Mushroom Tart,Appetizer - Sausage Rolls,Apricots - Dried,Apricots - Halves,Apricots Fresh,Arizona - Green Tea,Artichokes - Jerusalem,Assorted Desserts,...,"Wine - White, Colubia Cresh","Wine - White, Mosel Gold","Wine - White, Schroder And Schyl",Wine - Wyndham Estate Bin 777,Wonton Wrappers,Yeast Dry - Fermipan,Yoghurt Tubes,"Yogurt - Blueberry, 175 Gr",Yogurt - French Vanilla,Zucchini - Yellow
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
264,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
356,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
412,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
cust_prod_pivot2 = prod_cust_pivot2.T
cust_prod_pivot2.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Appetizer - Mini Egg Roll, Shrimp",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Appetizer - Mushroom Tart,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0
Appetizer - Sausage Rolls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,25.0,25.0,25.0,0.0,25.0,0.0
Apricots - Dried,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
prod_cust_pivot2 = prod_cust_pivot2.div(prod_cust_pivot2.sum(axis = 1), axis = 0)
cust_prod_pivot2 = cust_prod_pivot2.div(cust_prod_pivot2.sum(axis = 1), axis = 0)

In [17]:
cust_dist2 = pd.DataFrame(1/(1 + squareform(pdist(cust_prod_pivot2, 'euclidean'))),
                         index = cust_prod_pivot2.index, columns = cust_prod_pivot2.index)

cust_dist2.head()

ProductName,Anchovy Paste - 56 G Tube,"Appetizer - Mini Egg Roll, Shrimp",Appetizer - Mushroom Tart,Appetizer - Sausage Rolls,Apricots - Dried,Apricots - Halves,Apricots Fresh,Arizona - Green Tea,Artichokes - Jerusalem,Assorted Desserts,...,"Wine - White, Colubia Cresh","Wine - White, Mosel Gold","Wine - White, Schroder And Schyl",Wine - Wyndham Estate Bin 777,Wonton Wrappers,Yeast Dry - Fermipan,Yoghurt Tubes,"Yogurt - Blueberry, 175 Gr",Yogurt - French Vanilla,Zucchini - Yellow
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,1.000000,0.881127,0.882219,0.884604,0.890449,0.879859,0.885648,0.880852,0.886501,0.890573,...,0.884117,0.888124,0.886567,0.879578,0.875696,0.878427,0.886163,0.886564,0.887956,0.878223
"Appetizer - Mini Egg Roll, Shrimp",0.881127,1.000000,0.883877,0.880604,0.887930,0.881577,0.885241,0.890196,0.888646,0.883484,...,0.887569,0.887831,0.888033,0.881019,0.878720,0.871915,0.888702,0.890837,0.887661,0.882616
Appetizer - Mushroom Tart,0.882219,0.883877,1.000000,0.884708,0.883266,0.884124,0.886495,0.886072,0.887707,0.881019,...,0.886796,0.885968,0.885056,0.887445,0.882789,0.879286,0.890062,0.889960,0.889397,0.881077
Appetizer - Sausage Rolls,0.884604,0.880604,0.884708,1.000000,0.885025,0.885020,0.881992,0.883090,0.880745,0.881226,...,0.882793,0.886507,0.884984,0.886515,0.877195,0.868976,0.885470,0.884688,0.883661,0.877701
Apricots - Dried,0.890449,0.887930,0.883266,0.885025,1.000000,0.886792,0.887542,0.889058,0.886234,0.887162,...,0.886223,0.889001,0.890087,0.887478,0.878571,0.872542,0.892076,0.891209,0.889794,0.886477

### Step 2: Get the products purchased for a specific customer of your choice.

In [18]:
products_purchased_customer33 = list(customer_products2['ProductName'][customer_products2['CustomerID'] == 33].unique())
#products_purchased_customer33

### Step 3: For each product the customer purchased, get a list of the top 5 similar products. Package the lists into a nested list, flatten the list, and then filter out any products the customer has already purchased.

In [19]:
similar_products_customer33 = list()

for i in products_purchased_customer33:
    similar_products_customer33.append(cust_dist2[i].sort_values(ascending = False)[1:6].index.to_list())

#similar_products_customer33

In [20]:
similar_products_customer33_flat = list()
for i in similar_products_customer33:
    for e in i:
        similar_products_customer33_flat.append(e)

similar_products_customer33_flat.sort()
#similar_products_customer33_flat

In [21]:
similar_nonbought_products_customer33 = list()

for i in similar_products_customer33_flat:
    if i not in products_purchased_customer33:
        similar_nonbought_products_customer33.append(i)

#similar_nonbought_products_customer33

### Step 4: Count the number of times each similar product occurs in your filtered list. Sort and return a list containing the top 5 items.

In [22]:
top5_recom_products_customer33 = list(pd.Series(similar_nonbought_products_customer33).value_counts().head().index)
top5_recom_products_customer33

['Sun - Dried Tomatoes',
 'Spinach - Baby',
 'Beef - Montreal Smoked Brisket',
 'Cookies - Assorted',
 'Rosemary - Primerba, Paste']

### Step 5: Now that we have generated product recommendations for a single user, put the pieces together and iterate over a list of all CustomerIDs.

- Create an empty dictionary that will hold the recommendations for all customers.
- Create a list of unique CustomerIDs to iterate over.
- Iterate over the customer list performing steps 2 through 4 for each and appending the results of each iteration to the dictionary you created.

In [23]:
recommendations2 = {}

customers = list(customer_products2['CustomerID'].unique())

    
for i in customers:    
    products_purchased_customer = list(customer_products2['ProductName'][customer_products2['CustomerID'] == i].unique())
    
    similar_prod = list()

    for product in products_purchased_customer:
        similar_prod.append(cust_dist2[product].sort_values(ascending = False)[1:6].index.to_list())
    
    similar_prod = [x for sublist in similar_prod for x in sublist]
    
    for e in products_purchased_customer:
        if e in similar_prod:
            similar_prod.remove(e)
            
    top5_recom_products_customer = list(pd.Series(similar_prod).value_counts().head().index)


    recommendations2[i] = top5_recom_products_customer

### Step 6: Store the results in a Pandas data frame. The data frame should a column for Customer ID and then a column for each of the 5 product recommendations for each customer.

In [24]:
user_recs2 = pd.DataFrame.from_dict(recommendations2, orient = 'index').reset_index()
user_recs2.columns = ['CustomerID', 'Rec1', 'Rec2', 'Rec3', 'Rec4', 'Rec5']
user_recs2.sort_values('CustomerID')

,CustomerID,Rec1,Rec2,Rec3,Rec4,Rec5
450,33,Sun - Dried Tomatoes,Spinach - Baby,Beef - Montreal Smoked Brisket,"Rosemary - Primerba, Paste",Cookies - Assorted
791,200,"Chocolate - Semi Sweet, Calets","Rosemary - Primerba, Paste",Spinach - Baby,Oil - Shortening - All - Purpose,Rice - Jasmine Sented
526,264,"Rosemary - Primerba, Paste",Spinach - Baby,Sun - Dried Tomatoes,"Hickory Smoke, Liquid",Oil - Shortening - All - Purpose
844,356,Spinach - Baby,Beef - Montreal Smoked Brisket,"Rosemary - Primerba, Paste",Veal - Osso Bucco,Sun - Dried Tomatoes
451,412,"Rosemary - Primerba, Paste",Sun - Dried Tomatoes,Oil - Shortening - All - Purpose,V8 - Berry Blend,French Pastry - Mini Chocolate
...,...,...,...,...,...,...
448,97928,Oil - Shortening - All - Purpose,V8 - Berry Blend,Sun - Dried Tomatoes,Scallops - Live In Shell,Spinach - Baby
449,98069,Oil - Shortening - All - Purpose,"Chocolate - Semi Sweet, Calets",Spinach - Baby,Cookies - Assorted,"Hickory Smoke, Liquid"
960,98159,Oil - Shortening - All - Purpose,V8 - Berry Blend,Spinach - Baby,Sun - Dried Tomatoes,Cookies - Assorted
380,98185,Scallops - Live In Shell,V8 - Berry Blend,French Pastry - Mini Chocolate,Oil - Shortening - All - Purpose,Sun - Dried Tomatoes
606,98200,"Rosemary - Primerba, Paste",Spinach - Baby,Oil - Shortening - All - Purpose,Cookies - Assorted,V8 - Berry Blend

## Recommending Items to a New Customer

Suppose we get a new customer and on their first visit, they purchase the following items and quantities.

In [25]:
new_customer = {'Cookies - Assorted':3,
                'Flavouring - Orange':3,
                'Fenngreek Seed':1,
                'Wine - White Cab Sauv.on':1,
                'Bandage - Flexible Neon':3,
                'Oil - Shortening - All - Purpose':2,
                'Beef - Montreal Smoked Brisket':4,
                'French Pastry - Mini Chocolate':4,
                'Snapple Lemon Tea':5,
                'Pepper - White, Ground':2,
                'Spinach - Baby':5,
                'Sole - Dover, Whole, Fresh':4}

### Step 7: Recommend 5 products to this new customer using a user similarity approach.

In [26]:
#Vemos cual es el Ãºltimo ID de los clientes que tenemos
customer_products.CustomerID.unique()

array([   33,   200,   264,   356,   412,   464,   477,   639,   649,
         669,   694,   756,   883,   891,  1008,  1034,  1066,  1072,
        1336,  1428,  1435,  1534,  1577,  1594,  1754,  1839,  1920,
        2187,  2329,  2503,  2556,  2566,  2582,  2617,  2686,  2754,
        2776,  2902,  2915,  2939,  3074,  3253,  3267,  3305,  3317,
        3472,  3531,  3535,  3544,  3885,  3903,  3909,  4261,  4479,
        4595,  4644,  4723,  5104,  5177,  5183,  5224,  5230,  5434,
        5678,  5739,  5832,  5921,  5968,  5986,  5997,  6001,  6185,
        6317,  6352,  6367,  6447,  6543,  6734,  6817,  6851,  7021,
        7134,  7223,  7543,  7606,  7623,  7772,  7827,  7987,  7999,
        8316,  8367,  8372,  8539,  8711,  8917,  8962,  9047,  9132,
        9260,  9302,  9533,  9546,  9597,  9771,  9804, 10016, 10094,
       10114, 10224, 10311, 10418, 10739, 11023, 11057, 11083, 11102,
       11253, 11325, 11380, 11441, 11443, 11614, 11628, 11744, 11883,
       11933, 12059, 12206, 12232, 12381, 12529, 12561, 12596, 12598,
       12852, 12888, 13062, 13118, 13338, 13354, 13681, 13699, 13823,
       13912, 14012, 14208, 14501, 14782, 14910, 14913, 14977, 15027,
       15088, 15119, 15148, 15165, 15166, 15371, 15373, 15415, 15420,
       15672, 15796, 15851, 15888, 15920, 15986, 16139, 16375, 16481,
       16614, 16650, 16664, 16809, 16971, 16997, 17097, 17136, 17263,
       17390, 17404, 17407, 17458, 17472, 17760, 17765, 17906, 18027,
       18040, 18133, 18281, 18293, 18364, 18441, 18480, 18552, 18591,
       18622, 18680, 18683, 18688, 18706, 18720, 18728, 18760, 18796,
       19074, 19147, 19148, 19260, 19312, 19442, 19526, 19753, 20006,
       20125, 20134, 20331, 20433, 20446, 20476, 20648, 20901, 20907,
       21027, 21095, 21177, 21734, 21795, 21973, 22175, 22204, 22308,
       22322, 22345, 22408, 22454, 22461, 22508, 22536, 22705, 22751,
       22901, 22939, 22982, 23001, 23165, 23176, 23220, 23377, 23451,
       23515, 23548, 24137, 24271, 24323, 24435, 24490, 24554, 24820,
       25013, 25040, 25125, 25209, 25270, 25292, 25327, 25420, 25421,
       25449, 25624, 25651, 25703, 25779, 25994, 25995, 26031, 26353,
       26375, 26458, 26601, 26850, 26974, 27045, 27160, 27209, 27381,
       27410, 27546, 27572, 27669, 27672, 27760, 27821, 27826, 27841,
       27849, 27857, 28030, 28191, 28368, 28702, 28751, 28756, 28867,
       28875, 28976, 28984, 29095, 29258, 29287, 29342, 29444, 29475,
       29580, 29656, 29681, 29721, 29867, 29910, 29998, 30196, 30324,
       30423, 30451, 30575, 30803, 30815, 30954, 31075, 31100, 31113,
       31323, 31373, 31409, 31468, 31549, 31820, 32010, 32028, 32180,
       32324, 32373, 32386, 32558, 32575, 32584, 32682, 32753, 32785,
       32946, 33051, 33132, 33320, 33325, 33381, 33749, 33759, 33840,
       33878, 34184, 34291, 34657, 35028, 35034, 35107, 35531, 35575,
       35873, 35877, 36042, 36138, 36179, 36200, 36201, 36566, 36737,
       36740, 36751, 36829, 37495, 37510, 37619, 37873, 38048, 38125,
       38154, 38186, 38265, 38307, 38339, 38358, 38405, 38497, 38703,
       38798, 38890, 39110, 39280, 39537, 39552, 39757, 39813, 40094,
       40099, 40223, 40863, 40896, 40901, 40934, 40985, 41045, 41147,
       41286, 41319, 41405, 41538, 41722, 41747, 41829, 41834, 41843,
       42087, 42157, 42303, 42306, 42394, 42399, 42426, 42459, 42611,
       42612, 42776, 42802, 42819, 43270, 43345, 43529, 43589, 43652,
       44030, 44058, 44090, 44349, 44408, 44667, 44742, 44859, 45042,
       45266, 45313, 45420, 45498, 45549, 45582, 45598, 45754, 45759,
       45786, 45846, 45965, 46036, 46046, 46146, 46250, 46315, 46324,
       46367, 46482, 46551, 46659, 46715, 46807, 46826, 46910, 46971,
       47062, 47122, 47303, 47305, 47497, 47605, 47845, 47913, 47985,
       48108, 48139, 48156, 48534, 48611, 48641, 48642, 48655, 48818,
       48858, 48963, 49005, 49159, 49454, 49474, 49491, 49795, 49981,
       50004, 50098, 50416, 50435, 50461, 50497, 50535, 50670, 50748,
       50761, 50774, 51023, 51121, 51160, 51182, 51224, 51279, 51451,
       51483, 51631, 51718, 51742, 51834, 51934, 51939, 52024, 52091,
       52139, 52154, 52155, 52479, 52634, 52700, 53176, 53198, 53214,
       53226, 53501, 53729, 53851, 53997, 54001, 54093, 54495, 54547,
       54774, 54827, 54857, 54894, 54906, 55124, 55162, 55245, 55275,
       55281, 55380, 55381, 55580, 55715, 55780, 55875, 55876, 55930,
       55932, 56319, 56374, 56382, 56469, 56479, 56567, 56786, 56887,
       57024, 57090, 57168, 57241, 57317, 57459, 57497, 57606, 57654,
       57737, 57977, 57991, 58064, 58165, 58203, 58246, 58321, 58348,
       58353, 58366, 58413, 58421, 58535, 58639, 58652, 58874, 59017,
       59108, 59150, 59207, 59258, 59379, 59399, 59626, 59703, 59710,
       59711, 59831, 59925, 60185, 60378, 60389, 60481, 60515, 60612,
       60759, 60781, 60862, 60917, 60938, 60969, 61223, 61288, 61417,
       61601, 61750, 61923, 62005, 62034, 62094, 62101, 62184, 62242,
       62277, 62279, 62411, 62421, 62592, 62719, 63033, 63086, 63120,
       63295, 63368, 63742, 63771, 63803, 63891, 63963, 64117, 64202,
       64301, 64348, 64575, 64597, 64615, 64775, 64787, 64862, 65326,
       65535, 65650, 65678, 65731, 65757, 65785, 65830, 65875, 65910,
       65925, 66177, 66232, 66320, 66419, 66445, 66632, 66709, 66807,
       66822, 66987, 67058, 67061, 67203, 67281, 67428, 67473, 67582,
       67636, 67682, 68076, 68298, 68336, 68416, 68506, 68627, 68680,
       68699, 68829, 69027, 69397, 69906, 69931, 69967, 70017, 70324,
       70354, 70363, 70512, 70517, 70624, 70986, 71085, 71282, 71298,
       71595, 71844, 71948, 72056, 72063, 72152, 72305, 72311, 72330,
       72428, 72433, 72487, 72546, 72750, 72829, 72846, 73030, 73031,
       73190, 73280, 73353, 73609, 73614, 74077, 74213, 74237, 74403,
       74451, 74784, 75022, 75762, 75791, 75793, 76281, 76378, 76389,
       76442, 76475, 76511, 76530, 76532, 76690, 76796, 76983, 77037,
       77352, 77574, 77628, 77651, 77682, 77685, 77696, 77756, 77810,
       77814, 77950, 78048, 78054, 78082, 78104, 78133, 78252, 78297,
       78312, 78488, 78489, 78541, 78718, 78896, 78903, 78966, 78981,
       78993, 79060, 79068, 79141, 79189, 79230, 79290, 79353, 79458,
       79470, 79854, 79997, 80167, 80184, 80372, 80380, 80432, 80538,
       80694, 80782, 80849, 80890, 80898, 80938, 81001, 81012, 81034,
       81179, 81226, 81281, 81293, 81324, 81331, 81361, 81479, 81501,
       81591, 81696, 81715, 81813, 81845, 81876, 81981, 82057, 82146,
       82161, 82432, 82440, 82493, 82532, 82597, 82620, 82922, 83106,
       83158, 83355, 83495, 83608, 83940, 83973, 84280, 84349, 84364,
       84575, 84577, 84594, 84671, 84703, 84779, 84972, 85032, 85161,
       85246, 85292, 85437, 85480, 85496, 85524, 85552, 85642, 85766,
       85878, 85902, 86028, 86065, 86111, 86136, 86167, 86527, 86560,
       86595, 86625, 86662, 86786, 87030, 87228, 87285, 87303, 87408,
       87559, 87849, 87920, 87938, 87947, 87967, 88159, 88245, 88318,
       88533, 88552, 88733, 88769, 88855, 89110, 89181, 89254, 89272,
       89408, 89424, 89425, 89573, 89588, 89725, 90054, 90069, 90174,
       90193, 90284, 90300, 90347, 90508, 90694, 90776, 90777, 90933,
       91013, 91058, 91176, 91194, 91220, 91224, 91443, 91652, 91713,
       91777, 91783, 92067, 92139, 92168, 92255, 92418, 92492, 92525,
       92543, 92594, 92637, 92673, 92951, 92995, 93417, 93445, 93505,
       93540, 93692, 93882, 93918, 94258, 94420, 94438, 94547, 94599,
       94910, 94951, 95017, 95034, 95059, 95078, 95121, 95314, 95372,
       95819, 96024, 96088, 96272, 96522, 96524, 96560, 96615, 96666,
       96684, 97029, 97052, 97063, 97093, 97201, 97282, 97324, 97495,
       97697, 97753, 97769, 97793, 97900, 97928, 98069, 98159, 98185,
       98200])

In [27]:
#Vemos cual es el Ãºltimo Ã­ndice del dataframe que creamos con los productos resumidos por cliente
customer_products.tail()

       CustomerID                    ProductName  Quantity
63623       98200                   Vol Au Vents        50
63624       98200                  Wasabi Powder        25
63625       98200       Wine - Fume Blanc Fetzer        25
63626       98200  Wine - Hardys Bankside Shiraz        25
63627       98200        Yogurt - French Vanilla        25

In [28]:
customer_products.loc[63628] = [98201, 'Cookies - Assorted', 3]
customer_products.loc[63629] = [98201, 'Flavouring - Orange', 3]
customer_products.loc[63630] = [98201, 'Fenngreek Seed', 1]
customer_products.loc[63631] = [98201, 'Wine - White Cab Sauv.on', 1]
customer_products.loc[63632] = [98201, 'Bandage - Flexible Neon', 3]
customer_products.loc[63633] = [98201, 'Oil - Shortening - All - Purpose', 2]
customer_products.loc[63634] = [98201, 'Beef - Montreal Smoked Brisket', 4]
customer_products.loc[63635] = [98201, 'French Pastry - Mini Chocolate', 4]
customer_products.loc[63636] = [98201, 'Snapple Lemon Tea', 5]
customer_products.loc[63637] = [98201, 'Pepper - White, Ground', 2]
customer_products.loc[63638] = [98201, 'Spinach - Baby', 5]
customer_products.loc[63639] = [98201, 'Sole - Dover, Whole, Fresh', 4]

In [29]:
#Revisamos que se hayan agregado correctamente los productos del nuevo cliente
customer_products.tail(12)

       CustomerID                       ProductName  Quantity
63628       98201                Cookies - Assorted         3
63629       98201               Flavouring - Orange         3
63630       98201                    Fenngreek Seed         1
63631       98201          Wine - White Cab Sauv.on         1
63632       98201           Bandage - Flexible Neon         3
63633       98201  Oil - Shortening - All - Purpose         2
63634       98201    Beef - Montreal Smoked Brisket         4
63635       98201    French Pastry - Mini Chocolate         4
63636       98201                 Snapple Lemon Tea         5
63637       98201            Pepper - White, Ground         2
63638       98201                    Spinach - Baby         5
63639       98201        Sole - Dover, Whole, Fresh         4

In [30]:
prod_cust_pivot = customer_products.pivot_table(values = 'Quantity', 
                                                columns = 'CustomerID', 
                                                index = 'ProductName', 
                                                aggfunc = 'sum').fillna(0)

prod_cust_pivot.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97753,97769,97793,97900,97928,98069,98159,98185,98200,98201
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Appetizer - Mini Egg Roll, Shrimp",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Appetizer - Mushroom Tart,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0
Appetizer - Sausage Rolls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,25.0,25.0,25.0,0.0,25.0,0.0,0.0
Apricots - Dried,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
cust_prod_pivot = prod_cust_pivot.T
cust_prod_pivot.tail()

ProductName,Anchovy Paste - 56 G Tube,"Appetizer - Mini Egg Roll, Shrimp",Appetizer - Mushroom Tart,Appetizer - Sausage Rolls,Apricots - Dried,Apricots - Halves,Apricots Fresh,Arizona - Green Tea,Artichokes - Jerusalem,Assorted Desserts,...,"Wine - White, Colubia Cresh","Wine - White, Mosel Gold","Wine - White, Schroder And Schyl",Wine - Wyndham Estate Bin 777,Wonton Wrappers,Yeast Dry - Fermipan,Yoghurt Tubes,"Yogurt - Blueberry, 175 Gr",Yogurt - French Vanilla,Zucchini - Yellow
CustomerID,,,,,,,,,,,,,,,,,,,,,
98069,0.0,0.0,0.0,25.0,0.0,25.0,0.0,0.0,0.0,25.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98159,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,50.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0,0.0
98185,0.0,0.0,25.0,25.0,0.0,25.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0
98200,0.0,0.0,0.0,0.0,0.0,25.0,25.0,0.0,0.0,25.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0
98201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
prod_cust_pivot = prod_cust_pivot.div(prod_cust_pivot.sum(axis = 1), axis = 0)
cust_prod_pivot = cust_prod_pivot.div(cust_prod_pivot.sum(axis = 1), axis = 0)

In [33]:
cust_dist = pd.DataFrame(1/(1 + squareform(pdist(cust_prod_pivot, 'euclidean'))),
                         index=cust_prod_pivot.index, columns = cust_prod_pivot.index)

cust_dist.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97753,97769,97793,97900,97928,98069,98159,98185,98200,98201
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,1.000000,0.854082,0.859145,0.852783,0.856118,0.853239,0.849549,0.848801,0.851224,0.849892,...,0.846812,0.850301,0.841254,0.852221,0.846485,0.852848,0.847637,0.856465,0.851614,0.751984
200,0.854082,1.000000,0.857935,0.855900,0.856445,0.853129,0.863562,0.850521,0.857381,0.856621,...,0.856014,0.862447,0.854629,0.856670,0.854046,0.868990,0.857312,0.861508,0.857184,0.750250
264,0.859145,0.857935,1.000000,0.851801,0.860050,0.851262,0.855847,0.846677,0.854206,0.848997,...,0.850766,0.854178,0.848507,0.858909,0.860153,0.859773,0.854246,0.864699,0.853668,0.751996
356,0.852783,0.855900,0.851801,1.000000,0.852571,0.849431,0.853831,0.851902,0.847607,0.846328,...,0.848015,0.852222,0.847706,0.851413,0.851289,0.851219,0.852260,0.860721,0.854377,0.745769
412,0.856118,0.856445,0.860050,0.852571,1.000000,0.855755,0.858976,0.857221,0.854857,0.855991,...,0.862847,0.854943,0.850044,0.858385,0.856629,0.855052,0.856608,0.865269,0.862253,0.762370

In [34]:
recommendations = {}
customers = list(customer_products['CustomerID'].unique())

for customer in customers:
    similar_cust = list(cust_dist[customer].sort_values(ascending = False)[1:].head().index)
    sim_cust_prod = customer_products[customer_products['CustomerID'].isin(similar_cust)]
    grouped = sim_cust_prod.groupby('ProductName').agg({'Quantity':'sum'})
    ranked_products = grouped.sort_values('Quantity', ascending = False).reset_index()
    
    merged = pd.merge(ranked_products, pd.DataFrame(cust_prod_pivot.T[customer]), on = 'ProductName')
    merged.columns = ['ProductName', 'Quantity', 'Purchased']
    recs = merged[merged['Purchased'] == 0].head()
    recommendations[customer] = list(recs['ProductName'])

user_recs = pd.DataFrame.from_dict(recommendations, orient = 'index').reset_index()
user_recs.columns = ['CustomerID', 'Rec1', 'Rec2', 'Rec3', 'Rec4', 'Rec5']
user_recs.tail(1)

,CustomerID,Rec1,Rec2,Rec3,Rec4,Rec5
1000,98201,Ezy Change Mophandle,Foam Cup 6 Oz,"Coconut - Shredded, Sweet",Beets - Mini Golden,Veal - Sweetbread

### Step 8: Recommend 5 products to this new customer using a item similarity approach.

In [35]:
customer_products2

                     ProductName  CustomerID  Quantity
0      Anchovy Paste - 56 G Tube         639         1
1      Anchovy Paste - 56 G Tube         883         1
2      Anchovy Paste - 56 G Tube         891         1
3      Anchovy Paste - 56 G Tube        2566         1
4      Anchovy Paste - 56 G Tube        2902         1
...                          ...         ...       ...
63623          Zucchini - Yellow       94910        25
63624          Zucchini - Yellow       95078        25
63625          Zucchini - Yellow       95372        50
63626          Zucchini - Yellow       96024        25
63627          Zucchini - Yellow       96666        25

[63628 rows x 3 columns]

In [36]:
#Agregamos los productos comprados por el cliente nuevo
customer_products2.loc[63628] = ['Cookies - Assorted', 98201, 3]
customer_products2.loc[63629] = ['Flavouring - Orange', 98201, 3]
customer_products2.loc[63630] = ['Fenngreek Seed', 98201, 1]
customer_products2.loc[63631] = ['Wine - White Cab Sauv.on', 98201, 1]
customer_products2.loc[63632] = ['Bandage - Flexible Neon', 98201, 3]
customer_products2.loc[63633] = ['Oil - Shortening - All - Purpose', 98201, 2]
customer_products2.loc[63634] = ['Beef - Montreal Smoked Brisket', 98201, 4]
customer_products2.loc[63635] = ['French Pastry - Mini Chocolate', 98201, 4]
customer_products2.loc[63636] = ['Snapple Lemon Tea', 98201, 5]
customer_products2.loc[63637] = ['Pepper - White, Ground', 98201, 2]
customer_products2.loc[63638] = ['Spinach - Baby', 98201, 5]
customer_products2.loc[63639] = ['Sole - Dover, Whole, Fresh', 98201, 4]

In [37]:
prod_cust_pivot2 = customer_products2.pivot_table(values = 'Quantity', 
                                                columns = 'ProductName', 
                                                index = 'CustomerID', 
                                                aggfunc = 'sum').fillna(0)

prod_cust_pivot2.head()

ProductName,Anchovy Paste - 56 G Tube,"Appetizer - Mini Egg Roll, Shrimp",Appetizer - Mushroom Tart,Appetizer - Sausage Rolls,Apricots - Dried,Apricots - Halves,Apricots Fresh,Arizona - Green Tea,Artichokes - Jerusalem,Assorted Desserts,...,"Wine - White, Colubia Cresh","Wine - White, Mosel Gold","Wine - White, Schroder And Schyl",Wine - Wyndham Estate Bin 777,Wonton Wrappers,Yeast Dry - Fermipan,Yoghurt Tubes,"Yogurt - Blueberry, 175 Gr",Yogurt - French Vanilla,Zucchini - Yellow
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
264,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
356,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
412,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
cust_prod_pivot2 = prod_cust_pivot2.T
cust_prod_pivot2.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97753,97769,97793,97900,97928,98069,98159,98185,98200,98201
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Appetizer - Mini Egg Roll, Shrimp",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Appetizer - Mushroom Tart,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0
Appetizer - Sausage Rolls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,25.0,25.0,25.0,0.0,25.0,0.0,0.0
Apricots - Dried,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
prod_cust_pivot2 = prod_cust_pivot2.div(prod_cust_pivot2.sum(axis = 1), axis = 0)
cust_prod_pivot2 = cust_prod_pivot2.div(cust_prod_pivot2.sum(axis = 1), axis = 0)

In [40]:
cust_dist2 = pd.DataFrame(1/(1 + squareform(pdist(cust_prod_pivot2, 'euclidean'))),
                         index = cust_prod_pivot2.index, columns = cust_prod_pivot2.index)

cust_dist2.head()

ProductName,Anchovy Paste - 56 G Tube,"Appetizer - Mini Egg Roll, Shrimp",Appetizer - Mushroom Tart,Appetizer - Sausage Rolls,Apricots - Dried,Apricots - Halves,Apricots Fresh,Arizona - Green Tea,Artichokes - Jerusalem,Assorted Desserts,...,"Wine - White, Colubia Cresh","Wine - White, Mosel Gold","Wine - White, Schroder And Schyl",Wine - Wyndham Estate Bin 777,Wonton Wrappers,Yeast Dry - Fermipan,Yoghurt Tubes,"Yogurt - Blueberry, 175 Gr",Yogurt - French Vanilla,Zucchini - Yellow
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,1.000000,0.881127,0.882219,0.884604,0.890449,0.879859,0.885648,0.880852,0.886501,0.890573,...,0.884117,0.888124,0.886567,0.879578,0.875696,0.878427,0.886163,0.886564,0.887956,0.878223
"Appetizer - Mini Egg Roll, Shrimp",0.881127,1.000000,0.883877,0.880604,0.887930,0.881577,0.885241,0.890196,0.888646,0.883484,...,0.887569,0.887831,0.888033,0.881019,0.878720,0.871915,0.888702,0.890837,0.887661,0.882616
Appetizer - Mushroom Tart,0.882219,0.883877,1.000000,0.884708,0.883266,0.884124,0.886495,0.886072,0.887707,0.881019,...,0.886796,0.885968,0.885056,0.887445,0.882789,0.879286,0.890062,0.889960,0.889397,0.881077
Appetizer - Sausage Rolls,0.884604,0.880604,0.884708,1.000000,0.885025,0.885020,0.881992,0.883090,0.880745,0.881226,...,0.882793,0.886507,0.884984,0.886515,0.877195,0.868976,0.885470,0.884688,0.883661,0.877701
Apricots - Dried,0.890449,0.887930,0.883266,0.885025,1.000000,0.886792,0.887542,0.889058,0.886234,0.887162,...,0.886223,0.889001,0.890087,0.887478,0.878571,0.872542,0.892076,0.891209,0.889794,0.886477

In [41]:
products_purchased_customer98201 = list(customer_products2['ProductName'][customer_products2['CustomerID'] == 98201].unique())
#products_purchased_customer98201

In [42]:
similar_products_customer98201 = list()

for i in products_purchased_customer98201:
    similar_products_customer98201.append(cust_dist2[i].sort_values(ascending = False)[1:6].index.to_list())

#similar_products_customer98201

In [43]:
similar_products_customer98201_flat = list()
for i in similar_products_customer98201:
    for e in i:
        similar_products_customer98201_flat.append(e)

similar_products_customer98201_flat.sort()
#similar_products_customer98201_flat

In [44]:
similar_nonbought_products_customer98201 = list()

for i in similar_products_customer98201_flat:
    if i not in products_purchased_customer98201:
        similar_nonbought_products_customer98201.append(i)

#similar_nonbought_products_customer98201

In [45]:
top5_recom_products_customer98201 = list(pd.Series(similar_nonbought_products_customer98201).value_counts().head().index)
top5_recom_products_customer98201

['Beef - Chuck, Boneless',
 'Rice - Jasmine Sented',
 'Towels - Paper / Kraft',
 'Veal - Osso Bucco',
 'Initation Crab Meat']

In [46]:
#O de otra forma, podemos volver a correr el cÃ³digo para todos los clientes
recommendations2 = {}

customers = list(customer_products2['CustomerID'].unique())

    
for i in customers:    
    products_purchased_customer = list(customer_products2['ProductName'][customer_products2['CustomerID'] == i].unique())
    
    similar_prod = list()

    for product in products_purchased_customer:
        similar_prod.append(cust_dist2[product].sort_values(ascending = False)[1:6].index.to_list())
    
    similar_prod = [x for sublist in similar_prod for x in sublist]
    
    for e in products_purchased_customer:
        if e in similar_prod:
            similar_prod.remove(e)
            
    top5_recom_products_customer = list(pd.Series(similar_prod).value_counts().head().index)


    recommendations2[i] = top5_recom_products_customer

In [48]:
user_recs2 = pd.DataFrame.from_dict(recommendations2, orient = 'index').reset_index()
user_recs2.columns = ['CustomerID', 'Rec1', 'Rec2', 'Rec3', 'Rec4', 'Rec5']
user_recs2.sort_values('CustomerID').tail(1)

,CustomerID,Rec1,Rec2,Rec3,Rec4,Rec5
1000,98201,Rice - Jasmine Sented,"Beef - Chuck, Boneless",Towels - Paper / Kraft,Spinach - Baby,Initation Crab Meat